初めてのコミット
quel4-shun/NRIkadai pull request #1
Opened 2020-06-08 00:23 UTC by quel4-shun

HTMLのマークアップをしました

2020-06-08 03:42 UTC, choimake reviewed
コメントしました。

ソースコードレベル以外の部分での不具合として
- 画像が表示されない

という挙動が見受けられますので、こちらも合わせて対応お願いします。

2020-06-08 03:42 UTC, choimake commented on NRI/inndex.html
> +        <title>NRIの強み:ビジネスモデルの特徴</title>
meta情報に`description`要素を追加してください。
今回は模写なので、内容はなんでもいいです。
SEO的に重要な要素で、descriptionが無いホームページというのは基本存在しません。

今からSEOを意識しておきましょう。

2020-06-08 03:42 UTC, choimake commented on NRI/inndex.html
> +            <a href="#"><img src="/Users/muhakyu/Downloads/NRI/nri-logo.png" alt=""></a>
altには値を入れるようにしましょう。
他にも該当箇所があるので、合わせて対応お願いします。

2020-06-08 03:42 UTC, choimake commented on NRI/inndex.html
> +                        <li><a href="#">企業理念</a></li>
インデントがズレています。

2020-06-08 03:46 UTC, choimake commented
追記です。
htmlファイルは「inndex.html」->「index.html」に修正しておいてください。

2020-06-09 21:46 UTC, quel4-shun commented
やったこと

・meta情報にdescription要素を追加
・altに値を追加
・インデントのズレを修正
・画像の不具合を修正

2020-06-10 02:53 UTC, piasoratech requested changes
コメントしたので確認をお願いします。

2020-06-10 02:53 UTC, piasoratech commented on NRI/index.html
> +                <a href="#"><img src="/Users/muhakyu/NRIkadai/NRI/svg2.svg" alt="言語"></a>
ハンバーガーメニューの実装は今回不要ですが、ハンバーガーメニューの画像をキャプチャして表示するようにしてください。

2020-06-10 02:53 UTC, piasoratech commented on NRI/index.html
> +                <a href="#"><img src="/Users/muhakyu/NRIkadai/NRI/svg2.svg" alt="言語"></a>
絶対パスでの表記だとPC内のパスを合わせないと画像が正しく表示されないので、相対パスでの記載にしてください。

2020-06-10 02:53 UTC, piasoratech commented on NRI/index.html
> +</html>
ファイルの終わりは改行を入れましょう

2020-06-10 02:53 UTC, piasoratech commented on NRI/index.html
> +        <footer>
`footer`の始まりはここではなく、免責条項の部分からになるかと

2020-06-17 05:40 UTC, piasoratech requested changes
コメントしたので確認をお願いします

2020-06-17 05:40 UTC, piasoratech commented on NRI/index.html
> +</html>
ファイルの終わりの改行というのは一番最後の`html`タグの後に改行を入れるという意味での指摘でした。

2020-06-17 05:40 UTC, piasoratech commented on NRI/index.html
> +            <a href="#"><img src="/Users/muhakyu/NRIkadai/img/nri-logo.png" alt="NRI"></a>
このパスの指定は相対パスではないです。
他も同様です。
相対パス指定をしておかないと他のユーザーの環境では画像が表示されなくなってしまいます。

2020-06-18 03:00 UTC, piasoratech requested changes
コメントしたので確認をお願いします

2020-06-18 03:00 UTC, piasoratech commented on index.html
> +                    <img src="/Users/muhakyu/NRIkadai/img/story06_img_01.jpg" alt="NRIのデジタルビジネス戦略 画像">
ここがまだ直っていないですね

2020-06-18 03:29 UTC, piasoratech approved these changes
OKです！
CSS作成に移りましょう

2020-06-18 03:32 UTC, merged